# API HTTP test requests for VS code REST client

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3NSwibmFtZSI6IkthbWFsYSBIYXJyaXMiLCJ1c2VybmFtZSI6ImthbWFsYWhhcnJpcyIsImVtYWlsIjoia2FtYWxhQG1ldHJvcG9saWEuZmkiLCJyb2xlIjoidXNlciIsImlhdCI6MTc2Mjk1OTc1MiwiZXhwIjoxNzYzMDQ2MTUyfQ.Dj8MjnBLn_Qs1vtL5rEAyvAZe0NlI89FNIaH3VhyG9w

### Cats


### Get all cats
GET http://localhost:3000/api/v1/cats


### Get cat by ID
GET http://localhost:3000/api/v1/cats/84
Content-Type: application/json


### Get cat by user ID
GET http://localhost:3000/api/v1/cats/users/44
Authorization: Bearer {{token}}

### Get my cats (logged in user)
GET http://localhost:3000/api/v1/cats/user
Authorization: Bearer {{token}}


### Post new cat
POST  http://localhost:3000/api/v1/cats
Content-Type: application/json
Authorization: Bearer {{token}}

  {
    "cat_name": "Snuffi",
    "weight": 5,
    "birthdate": "2021-10-12",
    "filename": "https://loremflickr.com/320/240/cat3",
    "owner": 75
  }


### Modify existing cat
PUT http://localhost:3000/api/v1/cats/78
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "cat_name": "Muffy",
    "weight": 9,
    "birthdate": "2021-10-12",
    "filename": "https://loremflickr.com/320/240/cat3"
  }


### Delete cat by ID
DELETE http://localhost:3000/api/v1/cats/65
Authorization: Bearer {{token}}


### post new cat with image
POST http://127.0.0.1:3000/api/v1/cats HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary


--MyBoundary
Content-Disposition: form-data; name="cat_name"

Misu
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="owner"

60
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="file"; filename="dog.jpg"
Content-Type: image/jpg

< ./dog.jpg
--MyBoundary--


### Post new cat with image and thumbail creation
POST http://127.0.0.1:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer {{token}}

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Misu
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="file"; filename="dog.jpg"
Content-Type: image/jpeg

< ./dog.jpg
--MyBoundary--



### Users

### Get all users
GET http://localhost:3000/api/v1/users
Authorization: Bearer {{token}}


### Get user by ID
GET http://localhost:3000/api/v1/users/70
Content-Type: application/json



### Get my cats
GET http://localhost:3000/api/v1/cats/user
 Authorization: Bearer {{token}}



### Post new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Kamala Harris",
  "username": "kamalaharris",
  "email": "kamala@metropolia.fi",
  "role": "user",
  "password": "password"
}



### Update user Info
PUT http://localhost:3000/api/v1/users/68
Content-Type: application/json
Authorization: Bearer {{token}}

  {

    "name": "Kamala dao11",
    "username": "kamaladao11",
    "email": "kamaladao@metropolia.fi",
    "role": "user",
    "password": "password"
  }


### Delete user
DELETE http://localhost:3000/api/v1/users/68
Authorization: Bearer {{token}}


### Login

### Post auth/login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

  {
    "username": "kamalaharris",
    "password": "password"
  }

### Get my user info
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer {{token}}

